@extends('layouts.index')
@section('content-index')
    @include('frontend.contents.services.header')
    @include('frontend.contents.services.service-section')
    @include('frontend.contents.services.features')
    @include('frontend.contents.services.service-card')
    @include('frontend.contents.partials.newsletter')
    @include('frontend.contents.partials.contact-section')
@endsection